name: my-first-action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo "Welcome to my first GitHub Action"

      - name: List files
        run: ls -la
