name: my-first-action

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: welcome
        run: echo "Welcome to my first action"

      - name: list files
        run: ls -la
        