name: generate-ascii
on :
  push

jobs:
  generate-ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run shell script
        run: |
          chmod +x .github/workflows/ascii-script.sh
          .github/workflows/ascii-script.sh

      - name: show files in the directory
        run: ls -ltra   

