name: Hello GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hello
        run: echo "Hello from GitHub Actions"

      - name: Show current directory
        run: |
          pwd  
          ls -la

      - name: generating ascii art
        run: cowsay -f "Hello from GitHub Actions" >> dragon.txt